### ISSUE TITLE
Out of memory error during training

### ISSUE THREAD

**Issue by yiikou** [jeromepaul/jForest#2]
Hi, the idea of calculating chi-square is bravo! I tried to use jForest with my dataset (10w rows with 30 feature) but it turned out out of memory error 
![](https://lh3.googleusercontent.com/-VyZrjAm6c_I/W0egOZb9_mI/AAAAAAAABoY/3z-sHYKu-WEbIvH6NrxYMt32whvSw2X1QCL0BGAYYCw/h53/2018-07-12.png)

Is it possible to optimize jForest in big data situation?

**Comment by jeromepaul** [comment]
Hi,

Thanks for your feedback.
The memory is handled by the rJava package.
You can initialise rJava with more memory by running
```
library(rJava)
.jinit(parameters="-Xmx4g")
```
before loading the jForest package.

Let me know if it solved your problem !

Cheers

**Comment by yiikou** [comment]
@jeromepaul It works! Thank you very much!
